auctions123/Controllers/AdministratorController.cs
using auctions123.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace auctions123.Controllers
{
    public class AdministratorController : Controller
    {
        private Model1 db = new Model1();
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Auctions
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            logger.Info("Admin/Index/ ");
            return View(db.Auctions.ToList());
        }

        // GET: Auctions/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            logger.Info("Admin/Details/ ");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }
            return View(auction);
        }

        // GET: Auctions/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Auctions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        //try to bind auctionModel
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AuctionViewModel auctionModel)
        {
            logger.Info("Admin/Create/ ");
            auctionModel.auction.image = new byte[auctionModel.ImageToUpload.ContentLength];
            auctionModel.ImageToUpload.InputStream.Read(auctionModel.auction.image, 0, auctionModel.auction.image.Length);
            auctionModel.auction.dateCreated = DateTime.Now;
            auctionModel.auction.stage = "READY";
            auctionModel.auction.priceChange = 0;
            db.Auctions.Add(auctionModel.auction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Auctions/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            logger.Info("Admin/Edit/id ");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null || auction.stage != "READY")
            {
                return HttpNotFound();
            }
            return View(auction);
        }

        // POST: Auctions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdAuction,price")]EditViewModel auctionEdit)
        {
            logger.Info("Admin/Edit/id ");
            var auction = db.Auctions.Find(auctionEdit.IdAuction);
            auction.price = auctionEdit.price;
            if (ModelState.IsValid)
            {
                db.Entry(auction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(auction);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Open(int? id)
        {
            logger.Info("Admin/Open/id ");
            if (ModelState.IsValid)
            {
                Auction auction = db.Auctions.Find(id);

                if (auction.stage == "OPEN") return RedirectToAction("Index");

                auction.stage = "OPEN";
                auction.dateOpened = DateTime.Now;
                db.Entry(auction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        // GET: Auctions/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            logger.Info("Admin/Delete/id ");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }
            return View(auction);
        }

        // POST: Auctions/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            logger.Info("Admin/DeleteConfirmed/id ");
            Auction auction = db.Auctions.Find(id);
            if (auction.LastBidders.Count > 0)
            {
                var lastBidder = db.LastBidders.SingleOrDefault(a => a.IdAuction == id);
                lastBidder.Status_ = "DELETED";
                db.Entry(lastBidder).State = EntityState.Modified;
            }

            auction.stage = "DELETED";
            db.Entry(auction).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

auctions123/Views/Administrator/Create.cshtml
@model auctions123.Models.AuctionViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Administrator", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Auction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.auction.productName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.auction.productName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.auction.productName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.auction.duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.auction.duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.auction.duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.auction.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.auction.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.auction.price, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ImageToUpload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageToUpload, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImageToUpload, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

auctions123/Views/Administrator/Delete.cshtml
@model auctions123.Models.Auction

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Auction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateOpened)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateClosed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateClosed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="data:image;base64,@System.Convert.ToBase64String(Model.image)" style="height:50px; width:50px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

auctions123/Views/Administrator/Details.cshtml
@model auctions123.Models.Auction

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Auction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateOpened)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateClosed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateClosed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="data:image;base64,@System.Convert.ToBase64String(Model.image)" style="height:200px; width:200px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdAuction }) |
    @Html.ActionLink("Back to List", "Index")
</p>

auctions123/Views/Administrator/Edit.cshtml
@model auctions123.Models.Auction

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Auction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdAuction)

        <div class="form-group">
            @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.stage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.image)" style="height:200px; width:200px;" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

auctions123/Views/Administrator/Index.cshtml
@model IEnumerable<auctions123.Models.Auction>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.productName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateOpened)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateClosed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.stage)
        </th>
        <th>
           @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    if (item.stage != "DELETED")
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.productName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateOpened)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateClosed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stage)
            </td>
            <td>
                <img src="data:image;base64,@System.Convert.ToBase64String(item.image)" style="height:200px; width:200px;"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @if (item.stage == "READY")
                {
                   @Html.ActionLink("Edit", "Edit", new { id = item.IdAuction }) <text>|</text> 
                   @Html.ActionLink("Open", "Open", new { id = item.IdAuction }) <text>|</text>
                }
                @Html.ActionLink("Details", "Details", new { id = item.IdAuction }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdAuction })
            </td>
        </tr>
        }
    }

</table>